name: pokeapi
description: PokeAPI Package
version: 1.0.3
homepage: "https://github.com/prathanbomb/pokedart"

environment:
    sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
